version: '1'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '5050:80'
