version: '3.8'
name: irecommend
services:
  app:
    depends_on:
      - postgres
      - redis
      - migrations
    build:
      target: production
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:4000

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/data

  migrations:
    build:
      target: migration
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
